name: account_book
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.66.2

  cupertino_icons: ^1.0.2

  bloc: ^8.0.3

  flutter_bloc: ^8.0.1

  equatable: ^2.0.3

  flutter_easyrefresh: ^2.2.1

  introduction_screen: ^3.0.2

  video_player: ^2.4.5

  rxdart: ^0.27.4

  # 月曆套件
  table_calendar: ^3.0.6

  # date picker
  flutter_datetime_picker_plus: ^2.1.0

  # 換頁動畫
  page_transition: ^2.0.9

  date_format: ^2.0.6

  shared_preferences: ^2.0.15

  # 滑動ListTile
  flutter_slidable: ^3.1.0

  uuid: ^3.0.6

  flutter_draggable_gridview: ^0.0.7

  flutter_statusbarcolor_ns: ^0.4.0

  easy_dynamic_theme: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

#  assets:
#    - psyduck.png
